# Generated by Django 3.2 on 2021-04-21 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adr_phys', models.CharField(max_length=100)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('cotisation', models.BigIntegerField()),
                ('nbr_paiement', models.SmallIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('linkedin', models.CharField(max_length=100)),
                ('statut', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField(default=False)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activite_presences', to='api.activite')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membre_presences', to='api.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.URLField()),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.activite')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraphe', models.CharField(max_length=1000)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='api.activite')),
            ],
        ),
        migrations.CreateModel(
            name='ContactNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nummembre', to='api.membre')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr_mail', models.EmailField(max_length=100, unique=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailmembre', to='api.membre')),
            ],
        ),
        migrations.CreateModel(
            name='ContactFb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_compte', models.CharField(max_length=200, unique=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbmembre', to='api.membre')),
            ],
        ),
        migrations.AddField(
            model_name='activite',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.categorie'),
        ),
    ]
