# Generated by Django 3.2 on 2021-04-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210422_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
