# Generated by Django 3.2 on 2021-06-15 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210422_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=150, null=True)),
                ('numero', models.CharField(max_length=20)),
                ('bancaire', models.CharField(max_length=25)),
                ('facebook', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(default='', max_length=300)),
                ('montant', models.BigIntegerField(default=0)),
                ('activite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activite', to='api.activite')),
            ],
        ),
        migrations.RemoveField(
            model_name='membre',
            name='cotisation',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='nbr_paiement',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='photo',
        ),
        migrations.AddField(
            model_name='presence',
            name='contrepresence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='api.activite'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='api.membre'),
        ),
        migrations.CreateModel(
            name='Regle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField(default=0)),
                ('description', models.CharField(default='', max_length=150)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles', to='api.activite')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photoprofil', to='api.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField()),
                ('ref', models.CharField(max_length=100)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiementcotisation', to='api.cotisation')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiementmembre', to='api.membre')),
            ],
        ),
    ]
