# Generated by Django 3.2 on 2021-06-10 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=150, null=True)),
                ('numero', models.CharField(max_length=20)),
                ('bancaire', models.CharField(max_length=25)),
                ('facebook', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField(default=0)),
                ('ref', models.CharField(max_length=30)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisation_membre', to='api.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Regle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField(default=0)),
                ('description', models.CharField(default='', max_length=150)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regle_activite', to='api.activite')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='presence',
            name='contrepresence',
            field=models.BooleanField(default=False),
        ),
    ]
