# Generated by Django 3.2 on 2021-06-16 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_activite_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.categorie'),
        ),
    ]
