# Generated by Django 3.2 on 2021-06-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210610_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='cotisation',
        ),
    ]
