# Generated by Django 3.2 on 2021-06-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_activite_categorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presence',
        ),
    ]
