# Generated by Django 3.2 on 2021-06-17 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_presence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField(default=False)),
                ('contrepresence', models.BooleanField(default=False)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='api.activite')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='api.membre')),
            ],
        ),
    ]
