# Generated by Django 3.2 on 2021-06-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210610_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Regle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField(default=0)),
                ('description', models.CharField(default='', max_length=150)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles', to='api.activite')),
            ],
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField(default=0)),
                ('ref', models.CharField(max_length=30)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='api.membre')),
            ],
        ),
        migrations.CreateModel(
            name='ContactOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=150, null=True)),
                ('numero', models.CharField(max_length=20)),
                ('bancaire', models.CharField(max_length=25)),
                ('facebook', models.CharField(max_length=100)),
                ('association', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contactorganisations', to='api.association')),
            ],
        ),
        migrations.AddField(
            model_name='activite',
            name='association',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='association_activites', to='api.association'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='association',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='association_categories', to='api.association'),
        ),
        migrations.AddField(
            model_name='membre',
            name='association',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='association_membres', to='api.association'),
        ),
    ]
