# Generated by Django 3.2 on 2021-06-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='api.activite'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='api.membre'),
        ),
    ]
