# Generated by Django 3.2 on 2021-06-17 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_presence_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprofil',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photoprofil', to='api.membre'),
        ),
    ]
