# Generated by Django 3.2 on 2021-06-17 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_photoprofil_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprofil',
            name='membre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photoprofil', to='api.membre'),
        ),
    ]
