# Generated by Django 3.2 on 2021-06-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_photoprofil_membre'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='membre',
        #    name='statut',
        #),
    ]
