# Generated by Django 3.2 on 2021-06-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_membre_statut'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='membre',
        #    name='statut',
        #    field=models.CharField(default=1, max_length=100),
        #    preserve_default=False,
        #),
    ]
