# Generated by Django 3.2 on 2021-06-20 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutmembre', to='api.statut'),
        ),
    ]
