# Generated by Django 3.2 on 2021-06-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_membre_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='mdp',
            field=models.CharField(default='membre951haikintana', max_length=30),
        ),
    ]
