# Generated by Django 3.2 on 2021-06-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_membre_mdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='titre',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
