# Generated by Django 3.2 on 2021-06-26 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_description_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.categorie'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.description'),
        ),
    ]
