# Generated by Django 3.2 on 2021-06-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210626_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='activite',
            new_name='description',
        ),
    ]
