# Generated by Django 3.2 on 2021-06-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_activite_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprofil',
            name='photo',
            field=models.ImageField(default='image/profil.jpg', upload_to='images'),
        ),
    ]
