# Generated by Django 3.2 on 2021-06-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_photoprofil_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprofil',
            name='photo',
            field=models.ImageField(default='profil.jpg', upload_to='images'),
        ),
    ]
