# Generated by Django 3.2 on 2021-06-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_photoprofil_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprofil',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
